---
title: "Workshop4_Spatial"
output: html_document
date: "2024-05-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading packages

#library(tidyverse)
#install.packages("sf") 
#install.packages("terra")
#install.packages("tmap")
library(tidyr)
library(sf) # simple features
library (terra) # for raster
library(tmap) # Thematic maps are geographical maps in which spatial data distributions are visualized

```

```{r}
library(readr)
dat <- read_csv("../data/copepods_raw.csv")
```

```{r}
# Creating a figure that plots our spatial data, but isnt neccessarily spatially accurate
library(ggplot2)
ggplot(dat) + 
  aes(x = longitude, y = latitude, color = richness_raw) +
  geom_point()
```

```{r}
#So, now let’s look at the richness data 

ggplot(dat, aes(x = latitude, y = richness_raw)) + 
  stat_smooth() + 
  geom_point()
```


```{r}
#turn our point data into a spatially referenced data frame

sdat <- st_as_sf(dat, coords = c("longitude", "latitude"), 
                 crs = 4326)

```


```{r}
#Coordinate reference systems
#Our copepod coordinates are long-lat, so we chose a common ‘one-size-fits-all’ GCS called WGS84 to define the crs using the EPSG code 4326.

crs4326 <- st_crs(4326)
crs4326 # look at the whole CRS
crs4326$Name # pull out just the name of the crs
crs4326$wkt  # crs in well-known text format

```

```{r}
#Feature collection (points)
sdat

```
```{r}
# Cartography

# Plotting Richness
plot(sdat["richness_raw"])

plot(sdat)
```
```{r}
#Thematic maps for communication

#Build and add on layers using using tmap 

tm1<- tm_shape(sdat) + 
  tm_dots(col = "richness_raw")


```

```{r}
# Saving our figure
tmap_save(tm1, filename = "Richness-map.png", 
          width = 600, height = 600)

```

```{r}
# Mapping spatial polygons as layers

# First, load spatial data
aus <- st_read("../data/spatial-data/Aussie/Aussie.shp")
shelf <- st_read("../data/spatial-data/aus_shelf/aus_shelf.shp")

```




```{r}
# Mapping your polygons

tm_shape(shelf) + 
  tm_polygons()

# Layering copepod data points
tm_shape(shelf, bbox = sdat) + 
  tm_polygons() +
  tm_shape(aus) + 
  tm_polygons() + 
  tm_shape(sdat) + 
  tm_dots()


```

```{r}
#Exploring t_map
vignette('tmap-getstarted')


tm_shape(shelf) + 
  tm_polygons()

# Adding additional element, such as colors
tm_shape(shelf, bbox = sdat) + 
  tm_polygons() +
  tm_shape(aus) + 
  tm_polygons() + 
  tm_shape(sdat) + 
  tm_dots(size = 0.01, col = "blue")


```
```{r}
# Vignette Exercises

# World map 
data("World") +
  tm_shape(World) +
    tm_polygons("HPI")

```

```{r}
# Multiple shapes and layers

data(World, metro, rivers, land)

tmap_mode("plot")
## tmap mode set to plotting
tm_shape(land) +
    tm_raster("elevation", palette = terrain.colors(10)) +
tm_shape(World) +
    tm_borders("white", lwd = .5) +
    tm_text("iso_a3", size = "AREA") +
tm_shape(metro) +
    tm_symbols(col = "red", size = "pop2020", scale = .5) +
tm_legend(show = FALSE)
```

```{r}
# Facets
tmap_mode("view")
tm_shape(World) +
    tm_polygons(c("HPI", "economy")) +
    tm_facets(sync = TRUE, ncol = 2)
```

```{r}
#Splitting the spatial data
tmap_mode("plot")
## tmap mode set to plotting

data(NLD_muni)
tm1 <- tm_shape(NLD_muni) + tm_polygons("population", convert2density = TRUE)
tm2 <- tm_shape(NLD_muni) + tm_bubbles(size = "population")

tmap_arrange(tm1, tm2)
```

```{r}
#Basemaps and overlay tile maps

tmap_mode("view")
tm_basemap("Stamen.Watercolor") +
tm_shape(metro) + tm_bubbles(size = "pop2020", col = "red") +
tm_tiles("Stamen.TonerLabels")
```

